#pragma config(Sensor, S1,     ultrasound,     sensorSONAR)
#pragma config(Sensor, S2,     light,          sensorLightActive)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define BLACK 40
#define POWER 50
float full_cicle = 0;
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**********************************************
 * Lab 3 : Starter code
 * Written by Kaushik Viswanathan,
 * Modified by Allan Wang (Jan 2017)
 * Feel free to modify any part of these codes.
 **********************************************/

//Global variables - you will need to change some of these
//Robot's positions
float robot_X = 0.0, robot_Y = 0.0, robot_TH = 0.0;

int velocityUpdateInterval = 5;
int PIDUpdateInterval = 2;

//Change these during demo

task followLine(){
	while(true){
//		motor[leftMotor]=30;
		float last_full = 0;
		nxtDisplayString(0,"ticks: %f", nMotorEncoder[leftMotor]);
		if(nNxtButtonPressed == kLeftButton){
			float full_circle = nMotorEncoder[leftMotor];
			nxtDisplayString(1,"total: %f", full_circle);
			//nMotorEncoder[leftMotor] = 0;
			//last_full = full_cicle; 
		}
		//if(nNxtButtonPressed == kRightButton){
		
		if(SensorValue(light)<BLACK){
			motor[leftMotor] = 20;
			motor[rightMotor] = 15;
			//temp = 1;
			//wait1Msec(10);
		}
		if(SensorValue(light)>BLACK){//on white
			motor[leftMotor] = 20;
			motor[rightMotor]=-10;
			}
			//wait1Msec(10);
		}
	}

task main()
{
	/* Reset encoders and turn on PID control */
	full_cicle = 0;
	nMotorEncoder[leftMotor] = 0;
	nMotorEncoder[rightMotor] = 0;
	nMotorPIDSpeedCtrl[leftMotor] = mtrSpeedReg;
	nMotorPIDSpeedCtrl[rightMotor] = mtrSpeedReg;
	nPidUpdateInterval = PIDUpdateInterval;
	
	//draw_grid();
	startTask(followLine);
	//while(true){}
	//startTask(dead_reckoning);

	
	//motor[motorA] = 0;
	//motor[motorB] = 0;
	//nNxtButtonTask  = 0;
	while(nNxtButtonPressed != kExitButton) {}
}
